source 'https://github.com/CocoaPods/Specs.git'

target 'UIView-ZQuartz', :exclusive => true do
  pod "UIView-ZQuartz", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIView-ZQuartz", :path => "../"

  
end
